name: sc_vae_pytorch
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://conda.anaconda.org/dranew
  - bioconda
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025a=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - absl-py==2.2.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.16
    - aiosignal==1.3.2
    - anndata==0.10.8
    - anyio==4.8.0
    - arboreto==0.1.6
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - array-api-compat==1.11.2
    - arrow==1.3.0
    - async-lru==2.0.4
    - async-timeout==5.0.1
    - attrs==25.1.0
    - babel==2.17.0
    - beautifulsoup4==4.13.3
    - biom-format==2.1.17
    - biopython==1.85
    - bleach==6.2.0
    - boltons==25.0.0
    - bx-python==0.14.0
    - cffi==2.0.0
    - chex==0.1.89
    - click==8.1.8
    - cloudpickle==3.1.2
    - contextlib2==21.6.0
    - cramjam==2.11.0
    - crossmap==0.7.3
    - ctxcore==0.2.0
    - cycler==0.12.1
    - cytoolz==1.1.0
    - dask==2024.8.0
    - dask-expr==1.1.10
    - dcor==0.6
    - debugpy==1.8.13
    - dendropy==5.0.8
    - dill==0.4.0
    - distributed==2024.8.0
    - docrep==0.3.2
    - etils==1.5.2
    - fastjsonschema==2.21.1
    - fastparquet==2024.11.0
    - filelock==3.13.1
    - flax==0.8.5
    - fonttools==4.56.0
    - fqdn==1.5.1
    - frozendict==2.4.7
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - get-annotations==0.1.2
    - gseapy==1.1.11
    - h11==0.14.0
    - h5py==3.13.0
    - harmonypy==0.0.10
    - httpcore==1.0.7
    - httpx==0.28.1
    - humanize==4.12.2
    - igraph==0.9.11
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - interlap==0.2.7
    - ipykernel==6.29.5
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jax==0.4.30
    - jaxlib==0.4.30
    - jedi==0.19.2
    - jinja2==3.1.4
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.15.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - legacy-api-wrap==1.4.1
    - lightning==2.5.1
    - lightning-utilities==0.14.3
    - locket==1.0.0
    - loompy==3.0.8
    - lz4==4.4.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.7
    - matplotlib-venn==1.1.2
    - mdurl==0.1.2
    - mistune==3.1.2
    - ml-collections==0.1.1
    - ml-dtypes==0.4.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mudata==0.2.4
    - multidict==6.4.3
    - multipledispatch==1.0.0
    - multiprocessing-on-dill==3.5.0a4
    - narwhals==2.0.1
    - natsort==8.4.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - numexpr==2.10.2
    - numpy==1.23.5
    - numpy-groupies==0.11.3
    - numpyro==0.19.0
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.21.5
    - nvidia-nvtx-cu11==11.8.86
    - opt-einsum==3.4.0
    - optax==0.2.4
    - orbax-checkpoint==0.6.4
    - overrides==7.7.0
    - packaging==24.2
    - pandas==1.5.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - partd==1.4.2
    - pexpect==4.9.0
    - pillow==11.0.0
    - plotly==6.2.0
    - pptree==3.1
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - propcache==0.3.1
    - protobuf==6.30.2
    - psutil==7.0.0
    - pyarrow==12.0.1
    - pyarrow-hotfix==0.7
    - pybigwig==0.3.24
    - pycparser==2.23
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.2.3
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - pysam==0.17.0
    - pyscenic==0.12.1
    - python-dateutil==2.9.0.post0
    - python-igraph==0.9.11
    - python-json-logger==3.3.0
    - python-louvain==0.16
    - pytorch-lightning==2.5.1
    - pytorch-ranger==0.1.1
    - pytz==2025.1
    - pyzmq==26.2.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==14.0.0
    - scanpy==1.10.3
    - scikit-bio==0.7.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - scistree2==0.2.0
    - scvi-tools==1.1.6.post2
    - seaborn==0.13.2
    - send2trash==1.8.3
    - session-info==1.0.1
    - six==1.17.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - stdlib-list==0.11.1
    - sympy==1.13.1
    - tblib==3.2.2
    - tensorstore==0.1.69
    - terminado==0.18.1
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tinycss2==1.4.0
    - tomli==2.2.1
    - toolz==1.0.0
    - torch==2.6.0+cu118
    - torch-optimizer==0.3.0
    - torchaudio==2.6.0+cu118
    - torchmetrics==1.7.1
    - torchvision==0.21.0+cu118
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - triton==3.2.0
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - umap-learn==0.5.7
    - uri-template==1.3.0
    - urllib3==2.3.0
    - vireosnp==0.5.9
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.13
    - yarl==1.19.0
    - zict==3.0.0
    - zipp==3.21.0
prefix: /sibcb1/chenluonanlab6/panlinnuo/anaconda3/envs/sc_vae_pytorch
